config/routes.rb
Rails.application.routes.draw do
  resources :widgets

  root 'welcome#index'

  get 'myfams' => 'fams#my_fams'

  get 'start' => 'creators#start_fam'

  resources :fams, only: [:new]

end

app/models/creator.rb
class Creator < ActiveRecord::Base
  has_one :member
end

app/models/fam.rb
class Fam < ActiveRecord::Base
  has_many :members, dependent: :destroy
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_one :user
  belongs_to :fam
  belongs_to :creator
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :members
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController

  before_action :set_fam, only: [:name_fam]


  def edit_fam_app

  end

  # Enter name form submission
  def name_fam
    @fam = Fam.new
  end

  def save_name(family)
    family.save
  end

end

app/controllers/fams_controller.rb
class FamsController < ApplicationController
  before_action :all_fams, only: [:my_fams, :create]
  before_action :set_fam, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js


  def new
    @fam = Fam.new
  end

  def create
    Fam.create(:fams_params)
  end

  private

    def all_fams
      @fams = Fam.all
    end

  # # GET /campers/1
  # def show
  #
  # end
  #
  # # GET /campers/new
  # def new
  #   @camper = Camper.new
  # end
  #
  # # GET /campers/1/edit
  # def edit
  # end
  #
  # # POST /campers
  # # POST /campers.json
  # def create
  #   @camper = Camper.new(camper_params.merge(medicalcompleted: 'false', user_id: current_user.id))
  #
  #   respond_to do |format|
  #     if @camper.save
  #       format.html { redirect_to @camper, notice: 'Camper was successfully created.' }
  #     else
  #       format.html { render :new }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /campers/1
  # # PATCH/PUT /campers/1.json
  # def update
  #   respond_to do |format|
  #     if @camper.update(camper_params)
  #       format.html { redirect_to @camper, notice: 'Camper was successfully updated.' }
  #     else
  #       format.html { render :edit }
  #     end
  #   end
  # end
  #
  # # DELETE /campers/1
  # # DELETE /campers/1.json
  # def destroy
  #   @camper.destroy
  #   respond_to do |format|
  #     format.html { redirect_to campers_url, notice: 'Camper was successfully destroyed.' }
  #   end
  # end
  #
  # private
  # # Use callbacks to share common setup or constraints between actions.
  # def set_camper
  #   @camper = Camper.find(params[:id])
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  def fam_params
    params.require(:fam).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # GET /welcome
  def index

  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/creators/edit_fam_app.html.erb
<div ng-app="myApp" ng-controller="CreatorController as ctr" >

  <div class="loading" ng-hide="ctr.init()"><p>Loading ...</p></div>

  <div class="fill-screen" ng-init="activeMenu='all_fams'" ng-cloak>

    <div class="save"><span>save <i class="glyphicon glyphicon-save"></i></span></div>


    <div class="container-fluid bg-1 text-center banner">

      <div ng-show="activeMenu==='all_fams'" >
        <div class="showfams" >
            <div class="estfam" ng-repeat="fam in ctr.fams">{{fam}} <span>H</span></div>
          <div class="newfam-square"><i class="glyphicon glyphicon-plus"></i></div>
        </div>
      </div>

      <div ng-show="activeMenu==='name_fam'" >



          <div class="form-group media-middle">
            <label for="usr">Fam Name:</label>
            <input type="text" class="form-control" id="usr">
          </div>


      </div>

      <div ng-show="activeMenu==='settings'" >



        <p>When do you want your updates to be delivered?</p>
        <div class="form-group">
          <label for="sel1"></label>
          <select class="form-control" id="sel1">
            <option>7 pm Friday</option>
            <option>12 pm Saturday</option>
            <option>7 pm Saturday</option>
            <option>Custom</option>
          </select>
        </div>



      </div>


      <div ng-show="activeMenu==='terms'">



        <div class="checkbox">
          <label><input type="checkbox" value="">I accept the terms</label>
        </div>



      </div>


      <div ng-show="activeMenu==='notify_fam'">



        <div class="checkbox">
          <label><input type="checkbox" value="">I accept the terms</label>
        </div>



      </div>

  </div>



  <div id="edit-fam-nav" class="text-center steps navbar-fixed-bottom" >
    <span ng-click="activeMenu = 'all_fams'" ng-class="{active : activeMenu === 'all_fams'}" class="glyphicon glyphicon-plus"></span>
    <span ng-click="activeMenu = 'name_fam'" ng-class="{active : activeMenu === 'name_fam', grey : activeMenu === 'all_fams'}" class="glyphicon glyphicon-font"></span>
    <span ng-click="activeMenu = 'settings'" ng-class="{active : activeMenu === 'settings', grey : activeMenu === 'all_fams'}" class="glyphicon glyphicon-tasks"></span>
    <span ng-click="activeMenu = 'terms'" ng-class="{active : activeMenu === 'terms',  grey :activeMenu === 'all_fams'}" class="glyphicon glyphicon-check"></span>
    <span ng-click="activeMenu = 'notify_fam'" ng-class="{active : activeMenu === 'notify_fam',  grey :activeMenu === 'all_fams'}" class="glyphicon glyphicon-bullhorn"></span>
  </div>



  </div>

</div>

g

app/views/creators/start_fam.html.erb
<div class="bg-1 fill-page container">
  <h1>New to Fambreak?</h1>

  <p class="tinytext">You're about to make your Fambreak group.</p>
  <p class="tinytext">The members of your group will join by replying to a text message--you can edit it before it's sent.</p>
  <h4 style="font-weight: bold;">Don't worry if you need to abandon your creation. You can save and come back.</h4>

  <div class="text-center">
    <a href=<%= myfams_path %> data-turbolinks="false" style="display: block; color: #ffd480; font-size: 15vw; margin-top: 10vh;" class="glyphicon glyphicon-ok-circle"></a><br>
  </div>
</div>

app/views/fams/my_fams.erb
<div ng-app="myApp" ng-controller="CreatorController as ctr" >

  <div class="loading" ng-hide="ctr.init()"><p>Loading ...</p></div>

  <div class="fill-screen" ng-init="activeMenu='all_fams'" ng-cloak>




    <div class="container-fluid bg-1 text-center banner">

      <div ng-show="activeMenu==='all_fams'" >
        <div class="showfams" >

          <% @fams.each do |fam| %>
            <div class="estfam" ><%= fam.name %><span><%= fam.name[0] %></span></div>
          <% end %>
          <div class="newfam-square"><i class="glyphicon glyphicon-plus"></i></div>
        </div>

        <%# WILL NEED: ajax request for selected fam %>

      </div>

      <div ng-show="activeMenu==='name_fam'" >



          <div class="form-group media-middle">
            <label for="usr">Fam Name:</label>
            <input type="text" class="form-control" id="usr">
          </div>


      </div>

      <div ng-show="activeMenu==='settings'" >



        <p>When do you want your updates to be delivered?</p>
        <div class="form-group">
          <label for="sel1"></label>
          <select class="form-control" id="sel1">
            <option>7 pm Friday</option>
            <option>12 pm Saturday</option>
            <option>7 pm Saturday</option>
            <option>Custom</option>
          </select>
        </div>



      </div>


      <div ng-show="activeMenu==='terms'">



        <div class="checkbox">
          <label><input type="checkbox" value="">I accept the terms</label>
        </div>



      </div>


      <div ng-show="activeMenu==='notify_fam'">



        <div class="checkbox">
          <label><input type="checkbox" value="">I accept the terms</label>
        </div>



      </div>

  </div>


  <div id="edit-fam-nav" class="text-center navbar-fixed-bottom">
    <div class="save"><span>save <i class="glyphicon glyphicon-new-window"></i></span></div>
    <div class="steps" >
      <span ng-click="activeMenu = 'all_fams'" ng-class="{active : activeMenu === 'all_fams'}" class="glyphicon glyphicon-plus"></span>
      <span ng-click="activeMenu === 'all_fams' ? activeMenu = 'name_fam'" ng-class="{active : activeMenu === 'name_fam', grey : activeMenu === 'all_fams'}" class="glyphicon glyphicon-font"></span>
      <span ng-click="activeMenu === 'all_fams' ? activeMenu = 'settings'" ng-class="{active : activeMenu === 'settings', grey : activeMenu === 'all_fams'}" class="glyphicon glyphicon-tasks"></span>
      <span ng-click="activeMenu === 'all_fams' ? activeMenu = 'terms'" ng-class="{active : activeMenu === 'terms',  grey :activeMenu === 'all_fams'}" class="glyphicon glyphicon-check"></span>
      <span ng-click="activeMenu === 'all_fams' ? activeMenu = 'notify_fam'" ng-class="{active : activeMenu === 'notify_fam',  grey :activeMenu === 'all_fams'}" class="glyphicon glyphicon-bullhorn"></span>
    </div>
  </div>


  </div>

</div>

g

app/views/fams/my_fams.html.erb
<div ng-app="myApp" ng-controller="CreatorController as ctr" ng-cloak>

  <div id="loading">Loading ...</div>

  <div ng-init="init()"></div>

  <div class="fill-screen">

    <div class="container-fluid bg-1 text-center banner">

      <div class="container" ng-show="activeMenu==='all_fams'" >
        <div class="showfams row" >

          <% if @fams %>
            <% @fams.each do |fam| %>
              <div data-remote="true"
                   data-url="/update"
                   data-params="id=10"
                   data-method="put"
                   class="estfam col-xs-12 " ><span><%= fam.name[0] %></span><br><%= fam.name %></div>
            <% end %>
          <% end %>

            <div class="newfam-square col-xs-12"><i class="glyphicon glyphicon-plus"></i></div>
        </div>

        <div id="task-form" style="display:none;"></div>

        <%# WILL NEED: ajax request for selected fam %>

      </div>

      <div ng-show="activeMenu==='name_fam'" >



          <div class="form-group media-middle">
            <label for="usr">Fam Name:</label>
            <input type="text" class="form-control" id="usr">
          </div>


      </div>

      <div ng-show="activeMenu==='settings'" >



        <p>When do you want your updates to be delivered?</p>
        <div class="form-group">
          <label for="sel1"></label>
          <select class="form-control" id="sel1">
            <option>7 pm Friday</option>
            <option>12 pm Saturday</option>
            <option>7 pm Saturday</option>
            <option>Custom</option>
          </select>
        </div>



      </div>


      <div ng-show="activeMenu==='terms'">



        <div class="checkbox">
          <label><input type="checkbox" value="">I accept the terms</label>
        </div>



      </div>


      <div ng-show="activeMenu==='notify_fam'">



        <div class="checkbox">
          <label><input type="checkbox" value="">I accept the terms</label>
        </div>



      </div>

  </div>


  <div id="edit-fam-nav" class="row text-center navbar-fixed-bottom">
    <div class="save"><span>save <i class="glyphicon glyphicon-new-window"></i></span></div>
    <div class="steps row" >
      <span class="col-xs-1"/>
      <span ng-click="activeMenu = 'all_fams'" ng-class="{active : activeMenu === 'all_fams'}" class="col-xs-1 glyphicon glyphicon-plus"></span>
      <span class="col-xs-1"/>
      <span ng-click="activeMenu === 'all_fams' ? activeMenu = 'name_fam' : ''" ng-class="{active : activeMenu === 'name_fam', grey : activeMenu === 'all_fams'}" class="col-xs-1 glyphicon glyphicon-font"></span>
      <span class="col-xs-1"/>
      <span ng-click="activeMenu === 'all_fams' ? activeMenu = 'settings' : ''" ng-class="{active : activeMenu === 'settings', grey : activeMenu === 'all_fams'}" class="col-xs-1 glyphicon glyphicon-tasks"></span>
      <span class="col-xs-1"/>
      <span ng-click="activeMenu === 'all_fams' ? activeMenu = 'terms' : ''" ng-class="{active : activeMenu === 'terms',  grey : activeMenu === 'all_fams'}" class="col-xs-1 glyphicon glyphicon-check"></span>
      <span class="col-xs-1"/>
      <span ng-click="activeMenu === 'all_fams' ? activeMenu = 'notify_fam' : ''" ng-class="{active : activeMenu === 'notify_fam',  grey : activeMenu === 'all_fams'}" class="col-xs-1 glyphicon glyphicon-bullhorn"></span>
      <span class="col-xs-1"/>
    </div>
  </div>


  </div>

</div>

app/views/fams/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fambreak</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target="#myScrollspy" data-offset="15" >


<!-- side nav -->
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a href=<%= root_path %>>Home</a>
  <a href=<%= myfams_path %>  data-turbolinks="false">My Fams</a>
  <a href="#">Login</a>
  <a href="#">Contact</a>
  <span>©Fambreak 2017</span>
</div>

<!-- home icon -->
<div class="col-xs-3" id="myScrollspy">
  <div onclick="openNav()" class="container circle home" data-spy="affix">
    <i class="glyphicon glyphicon-menu-hamburger"></i>
  </div>
</div>


  <%= yield %>



<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
</script>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>


</html>

app/views/welcome/index.html.erb
<div class=" bg-1 text-center fill-page">



<%= image_tag "logo-transparent-white.png", class: 'logo-png' %>


<h3 class="index-name logo-font">Fambreak</h3>
<p class="subheading tinytext">Update the ones who should know.</p>

<div class="container home">
  <span><a class="white btn index-button" href=<%= start_path %> data-turbolinks="false"><i class="glyphicon glyphicon-circle-arrow-right"></i>Start using Fambreak</a></span>
  <span><a class="white btn index-button" href="#" style="display: none"><i class="glyphicon glyphicon-user"></i> Login</a></span>
</div>
<br>


</div>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>